### ISSUE TITLE
Bug in CompareNoCase for MSC_VER >= 1500 pem-com.cpp 

### ISSUE THREAD

**Issue by gary-fsh** [noloader/cryptopp-pem#1]
The following line looks to be wrong and causes a problem when trying to use encrypted RSA pem files.

    std::transform(t2.begin(), t2.end(), stdext::make_checked_array_iterator(**t1**.begin(), t1.size()), ByteToLower());

I believe it should be 
    std::transform(t2.begin(), t2.end(), stdext::make_checked_array_iterator(**t2**.begin(), t1.size()), ByteToLower());

**Comment by gary-fsh** [comment]
PR created to resolve issue

**Comment by noloader** [comment]
@gary-fsh,

My bad... I did not see this until not. Do we still need to merge this?

**Comment by gary-fsh** [comment]
I thought you already merged it
