### ISSUE TITLE
x509cert.cpp(89,85): error C2059: syntax error: ')'

### ISSUE THREAD

**Issue by GekkieHenkie** [noloader/cryptopp-pem#11]
One closing bracket too many in x509cert.cpp, line 89; it doesn't compile.

**Comment by noloader** [comment]
Thanks @GekkieHenkie.

Sorry about that. Those changes were not well tested.

You will also need [Commit fae99431186d](https://github.com/weidai11/cryptopp/commit/fae99431186d) on Crypto++ master.
