### ISSUE TITLE
Add x25519 and ed25519 keys

### ISSUE THREAD

**Issue by noloader** [noloader/cryptopp-pem#5]
Crypto++ 8.0 cut-in [x25519](https://github.com/weidai11/cryptopp/issues/761) and [ed25519](https://github.com/weidai11/cryptopp/issues/764) support. We need to add support for the keys.

Ping @alambrec. Do you want to take a stab at it?

**Comment by alambrec** [comment]
Currently, I don't have much time free, and I'm not familiar with x25519 and ed25519 keys. 
So, I can't contribute to the implementation for the moment ... sorry 

I will just try to complete self-test and add a basic `Makefile` for `cryptopp-pem` if you are agree ...

But thank you anyway 😃

**Comment by noloader** [comment]
Done...
